name: Deploy to GCP
on: push
jobs:
  gcp-templates:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: GCP Login
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '318.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Upload src folder to GCP bucket
        uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
        with:
          path: ./src
          destination: ${{ secrets.GCP_BUCKET_NAME }}
